services:
  app-service:
    build:
      context: ../app-service-backend
      dockerfile: ../app-service-backend/Dockerfile.local
    expose:
      - "8000:8000"
    depends_on: 
      auth-service:
        condition: service_started
      reverse-proxy:
        condition: service_started
    volumes:
      - ~/Repos/live-bootcamp/app-service-frontend/assets:/app/assets:ro
    environment:
      ASSETS_DIR: /app/assets
      AUTH_SERVICE_HOST: auth-service:3000
    labels:
      traefik.enable: "true"

      traefik.http.middlewares.secure-mw.redirectscheme.permanent: "false"
      traefik.http.middlewares.secure-mv.redirectscheme.scheme: "https"

      traefik.http.middlewares.app-mv.chain.middlewares: "secure-mv"

      traefik.http.middlewares.strip-app-mv.stripprefix.prefixes: "/app"

      traefik.http.routers.app-service.entrypoints: "web"
      traefik.http.routers.app-service.rule: "Host(`localhost`) && PathPrefix(`/app/`)"
      
      traefik.http.services.app-service.loadbalancer.server.port: "8000"

      traefik.http.routers.app-service-http.middlewares: "app-mv"
      traefik.http.routers.app-service-secure.entrypoints: "websecure"
      traefik.http.routers.app-service-secure.rule: "Host(`localhost`) && PathPrefix(`/app/`)"

      traefik.http.routers.app-service-secure.tls: "true"
      traefik.http.routers.app-service-secure.middlewares: "strip-app-mv"

  auth-service:
    build:
      context: ../auth-service-backend
      dockerfile: ../auth-service-backend/Dockerfile.local
    expose:
      - "3000:3000"
    depends_on:
      - reverse-proxy
    volumes:
      - ~/Repos/live-bootcamp/auth-service-frontend/assets:/app/assets:ro
    environment:
      ASSETS_DIR: /app/assets
      JWT_SECRET: "secret"
    labels:
      traefik.enable: "true"

      traefik.http.middlewares.secure-mw.redirectscheme.permanent: "false"
      traefik.http.middlewares.secure-mv.redirectscheme.scheme: "https"

      traefik.http.middlewares.auth-mv.chain.middlewares: "secure-mv"

      traefik.http.middlewares.strip-auth-mv.stripprefix.prefixes: "/auth"

      traefik.http.routers.auth-service.entrypoints: "web"
      traefik.http.routers.auth-service.rule: "Host(`localhost`) && PathPrefix(`/auth/`)"
      
      traefik.http.services.auth-service.loadbalancer.server.port: "3000"

      traefik.http.routers.auth-service-http.middlewares: "auth-mv"
      traefik.http.routers.auth-service-secure.entrypoints: "websecure"
      traefik.http.routers.auth-service-secure.rule: "Host(`localhost`) && PathPrefix(`/auth/`)"

      traefik.http.routers.auth-service-secure.tls: "true"
      traefik.http.routers.auth-service-secure.middlewares: "strip-auth-mv"
  
  reverse-proxy:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy-service/traefik.yml:/etc/traefik/traefik.yml
      - ./reverse-proxy-service/acme.json:/letsencrypt/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "false"
