global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

accessLog:
  format: common
  filePath: "/var/log/traefik/access.log"

api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    watch: true
    directory: "/etc/traefik/dynamic"
