global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

accessLog:
  format: common
  filePath: "/var/log/traefik/access.log"

api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "mateusz.placzek@gmail.com"
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: "web"

tls:
  options:
    default:
      minVersion: "VersionTLS12"

providers:
  docker:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
