  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  #   - name: Install sshpass
  #     run: sudo apt-get install sshpass

  #   - name: Copy compose.yml to droplet
  #     run: sshpass -v -p '${{ secrets.DROPLET_PASSWORD }}' scp -o StrictHostKeyChecking=no compose.yml root@${{ vars.DROPLET_IP }}:~/${{ env.APP_NAME }}

  #   - name: Deploy
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ vars.DROPLET_IP }}
  #       username: root
  #       password: ${{ secrets.DROPLET_PASSWORD }}
  #       script: |
  #         cd ~/${{ env.APP_NAME }}
  #         docker network inspect ${{ env.DOCKER_NETWORK_NAME }} >/dev/null 2>&1 || docker network create --driver bridge ${{ env.DOCKER_NETWORK_NAME }}
  #         export AUTH_SERVICE_HOST='${{ vars.DROPLET_IP }}/auth'
  #         docker compose down
  #         docker compose pull
  #         docker compose up -d
